Ilhasoft/weni-webchannel

src/components/Widget/components/Conversation/components/Sender/index.js, src/components/Widget/components/Conversation/index.js, src/components/Widget/components/Conversation/style.scss
- Changed the location of  'Powered by Push'
=> Changed the location of  'Powered by Push'

src/components/Widget/components/Conversation/components/Sender/index.js, src/components/Widget/components/Conversation/index.js, src/components/Widget/index.js, src/components/Widget/layout.js, src/index.js
- InputTextFieldHint is now modified based on chat initialization props
=> fix: inputTextFieldHint prop added to missing places

src/components/Widget/components/Conversation/components/Sender/index.js, src/store/reducers/metadataReducer.js
=> fix: quick-replies selection to userInput now working

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.1.3

CHANGELOG.md, package-lock.json, package.json, src/components/Widget/index.js
=> fix: initPayload not being sent when the chat was manually opened

CHANGELOG.md, README.md, package-lock.json, package.json, src/components/Widget/components/Conversation/components/Sender/components/Suggestions/index.js, src/components/Widget/components/Conversation/components/Sender/components/Suggestions/styles.scss, src/scss/variables.scss
=> Improve: Suggestions behavior and customizable colors

src/components/Widget/components/Conversation/components/Messages/index.js
=> fix: dropzone click behavior

package.json
=> chore: 2.1.1

src/components/Widget/index.js
- removed channel id from `uniqueFrom` and let it be more random
=> fix: removed channel id from uniqueFrom and let it be more random

src/components/Widget/index.js
- Keep pinging with an interval of 50 seconds If there's no interaction, maximum of 60 pings
=> feat: socket ping

package.json
=> chore: 2.2.0

index.js, package.json, src/components/Widget/index.js, src/index.js
- New `clientId` attribute to be used as part of the session identifier.
=> feat: clientId attribute

src/components/Widget/components/Conversation/index.js
=> fix: powered by

package.json
=> chore: release 2.3.1

CHANGELOG.md, package-lock.json, package.json, src/components/Widget/index.js
- Check if an incoming message has a timestamp greater than 15 minutes. If true, set a timeout to wait for a user message in two minutes, if no message is sent than the initPayload is sent to start the flow.
=> feat: check history for delayed trigger

README.md
=> Replace push to weni

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.6.0

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.8.0

src/index.js
=> fix: closing socket connection while connecting

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.8.1

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.9.0

src/components/Widget/components/Conversation/components/Messages/components/Message/styles.scss, src/components/Widget/components/Conversation/components/Sender/index.js, src/components/Widget/components/Conversation/components/Sender/style.scss, src/components/Widget/components/Conversation/style.scss, src/components/Widget/index.js, src/scss/common.scss
- Modified widget input into textarea to be able to send a text with linebreaks.
=> Feat: multiple lines input and preview

src/components/Widget/components/Conversation/components/Messages/components/Message/styles.scss, src/components/Widget/components/Conversation/components/Sender/index.js, src/components/Widget/components/Conversation/components/Sender/style.scss
=> fix: textarea style and behavior issues

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.10.1

src/components/Widget/components/Launcher/style.scss
=> fix: added z-index into unread-count

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.10.2

CHANGELOG.md, package-lock.json, package.json, src/store/actions/dispatcher.js, src/store/actions/index.js, src/store/reducers/behaviorReducer.js
- add customPayload option into open action
=> feat: add customPayload option into open action

CHANGELOG.md, package-lock.json, package.json
=> chore: release 2.12.0

CHANGELOG.md, index.js, package-lock.json, package.json, src/components/Widget/index.js, src/index.js, src/store/actions/actionTypes.js, src/store/actions/dispatcher.js, src/store/actions/index.js, src/store/reducers/behaviorReducer.js
- Removed dependency from websocket to handle token generation, now the token is passed as a prop to the Widget
=> Feat: New close session method

src/components/Widget/components/Conversation/components/Messages/components/VidReply/index.js, src/components/Widget/components/Conversation/components/Messages/styles.scss
- Handle youtube video urls to render as iframe embeds
- Fix typing indicator overflow when fullscreen is active
=> [FLOWS-1470] fix: youtube video rendering and typing indication fullscreen overflow

src/components/Widget/components/Conversation/components/Messages/index.js
- Fix formatDate to support timestamp;
=> [FLOWS - 2555] - Fix: Format Date

src/components/Widget/components/Conversation/components/Sender/index.js, src/components/Widget/components/Conversation/components/Sender/style.scss
=> [RS-280] Fixes Responsivity Bugs

dev/src/index.html, src/components/Widget/index.js
Start the application with open chat when the prop startFullScreen is true.
=> [RS - 327] Fix: start fulscreen

src/components/Widget/index.js
Dispatch openchat when startfullscreen is true.
=> [RS - 327] Fix: dispatch openchat when startfullscreen is true

CHANGELOG.md, package-lock.json, package.json, src/components/Widget/index.js
- Fix WebChat Socket retry modes to prevent Socket overload.
=> [RS - 330] Fix: WebChat Socket retry modes to prevent Socket overload

dev/src/index.html, index.js
=> chore: roll back to 2.19.2

dev/src/index.html, src/components/Widget/index.js
- Prevent automatic reconnection on forbidden error and completely close widget to prevent manual reconnections in these cases
=> feat: prevent reconnection on forbidden error

CHANGELOG.md, package-lock.json, package.json
=> chore: release 2.19.5

src/store/reducers/behaviorReducer.js
=> Feat: add postMessage for chat open/close events

CHANGELOG.md, package.json, src/components/Widget/components/Conversation/components/Messages/components/Message/index.js, src/components/Widget/components/Conversation/components/Messages/styles.scss, src/components/Widget/components/Conversation/components/Sender/index.js, src/components/Widget/index.js, src/index.js
* * [x] Bugfix
* * [x] Feature
* * [ ] Code style update (formatting, local variables)
* * [ ] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
* Ensures connection is closed before try to reconnect;
* Ignores URL image transformation if it is already in markdown format;
* Considers screen height on the input autofocus, preventing automatic keyboard from opening when the screen is too small;
* Fixes typing styling on the fullscreen mode;
* Skips custom delay typing when typing_start is received from the socket, preventing duplicated typing behavior;
* Increases typing maximum timeout to 50 seconds.
=> [HS-1819] General Bug Fixes and Improvements

CHANGELOG.md, package.json, src/components/Widget/components/Conversation/components/Messages/index.js
* * [x] Bugfix
* * [ ] Feature
* * [ ] Code style update (formatting, local variables)
* * [ ] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
* Prevents the global export of the lodash package (_ object) that could cause conflicts.
=> [HS-1837] Lodash: Prevents The Global Export

CHANGELOG.md, package.json, src/components/Widget/components/Conversation/components/Sender/index.js, src/components/Widget/index.js, src/utils/audioToMp3Blob.js
* * [x] Bugfix
* * [x] Feature
* * [ ] Code style update (formatting, local variables)
* * [ ] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
* Converts audio to mp3 before sending it to the socket, avoiding incompatibilities with IOs;
* Always calls customMessageDelay, even when its return value is not used;
* Fixes reconnection when the socket is closed.
=> [HS-1868] General Enhancements About Audio Conversion and Fixes
